example:
    baseUrl: http://localhost:8080
    oauth2:
        client:
            grant-type: client_credentials
            clientId: <clientId>
            clientSecret: <clientSecrect>
            accessTokenUri: https://<oktaURL>/oauth2/default/v1/token
            scope: custom_mod